language: node_js
node_js:
  - "0.10"

env:
  global:
    - SAUCE_USERNAME=eightmedia
    - SAUCE_ACCESS_KEY=s974a3041-9fa1-4710-94cd-3802d418ff79

before_script:
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
  - npm install -g grunt-cli

script:
  - grunt test